# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 16:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Denied'), (1, 'Pending'), (2, 'Approved')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='BookTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('date_booking', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('place_id', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=45, verbose_name=b'Tipo')),
                ('possui_projetor', models.CharField(choices=[(b'0', b'----'), (b'1', b'N\xc3\xa3o'), (b'2', b'Sim')], default=b'0', max_length=1, verbose_name=b'Possui Projetor?')),
                ('possui_quadro_branco', models.CharField(choices=[(b'0', b'----'), (b'1', b'N\xc3\xa3o'), (b'2', b'Sim')], default=b'0', max_length=1, verbose_name=b'Possui Quadro Branco?')),
                ('possui_quadro_negro', models.CharField(choices=[(b'0', b'----'), (b'1', b'N\xc3\xa3o'), (b'2', b'Sim')], default=b'0', max_length=1, verbose_name=b'Possui Quadro Negro?')),
                ('descricao', models.TextField(default=b'...', max_length=255, verbose_name=b'Descri\xc3\xa7\xc3\xa3o')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='booking.Building')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_place', to='booking.Place'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.ManyToManyField(related_name='booking_time', to='booking.BookTime'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
