# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20170822_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Denied'), (1, 'Pending'), (2, 'Approved')], default=1),
        ),
        migrations.AlterField(
            model_name='place',
            name='descricao',
            field=models.TextField(default='...', max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='place',
            name='possui_projetor',
            field=models.CharField(choices=[('0', '----'), ('1', 'Não'), ('2', 'Sim')], default='0', max_length=1, verbose_name='Possui Projetor?'),
        ),
        migrations.AlterField(
            model_name='place',
            name='possui_quadro_branco',
            field=models.CharField(choices=[('0', '----'), ('1', 'Não'), ('2', 'Sim')], default='0', max_length=1, verbose_name='Possui Quadro Branco?'),
        ),
        migrations.AlterField(
            model_name='place',
            name='possui_quadro_negro',
            field=models.CharField(choices=[('0', '----'), ('1', 'Não'), ('2', 'Sim')], default='0', max_length=1, verbose_name='Possui Quadro Negro?'),
        ),
        migrations.AlterField(
            model_name='place',
            name='tipo',
            field=models.CharField(max_length=45, verbose_name='Tipo'),
        ),
    ]
