# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[(b'', b'----'), (b'1', 'Without Approved'), (b'2', 'With Aprooved')], max_length=20),
        ),
    ]
