# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170820_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='departamento_pertence',
            field=models.CharField(choices=[('0', '----'), ('1', 'Recurso do ICEB'), ('2', 'DEBIO'), ('3', 'DECBI'), ('4', 'DECOM'), ('5', 'DEEST'), ('6', 'DEFIS'), ('7', 'DEMAT'), ('8', 'DEEMA'), ('9', 'DEQUI')], default=0, max_length=20, verbose_name='Departamento do Usu\xe1rio'),
        ),
    ]
