# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170822_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.BooleanField(default=False),
        ),
    ]
