# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170822_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.BooleanField(default=False, verbose_name='Reserva Imediata'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='departamento_pertence',
            field=models.CharField(choices=[('0', '----'), ('1', 'Recurso do ICEB'), ('2', 'DEBIO'), ('3', 'DECBI'), ('4', 'DECOM'), ('5', 'DEEST'), ('6', 'DEFIS'), ('7', 'DEMAT'), ('8', 'DEEMA'), ('9', 'DEQUI')], default=0, max_length=20, verbose_name='Departamento:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='registration_number',
            field=models.CharField(error_messages={'unique': 'Registration Number already used.'}, max_length=20, unique=True),
        ),
    ]
